version: 1.1.1-{build}
configuration: Release
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
- cmd: dotnet -p test\MongoDb.Bson.NodaTime.Tests test
artifacts:
- path: artifacts\bin\MongoDb.Bson.NodaTime\Release\*.nupkg
  name: nuget