version: 3.0.0-{build}
os: Visual Studio 2019
configuration: Release
before_build:
- dotnet restore
build_script:
- dotnet pack src/MongoDb.Bson.NodaTime/ -c %CONFIGURATION%
test_script:
- dotnet test test/MongoDb.Bson.NodaTime.Tests/MongoDb.Bson.NodaTime.Tests.csproj
artifacts:
- path: src\MongoDb.Bson.NodaTime\bin\Release\*.nupkg
  name: nuget
