version: 1.2.0-{build}
os: Visual Studio 2015
configuration: Release
before_build:
- dotnet restore
build_script:
- dotnet pack src/MongoDb.Bson.NodaTime/ -c %CONFIGURATION%
test_script:
- dotnet test test/MongoDb.Bson.NodaTime.Tests
artifacts:
- path: src\MongoDb.Bson.NodaTime\bin\Release\*.nupkg
  name: nuget